### ISSUE TITLE
PrecompileJSP Option during Application deployment causes PWC6112: Failed to load or instantiate TagExtraInfo class: org.

### ISSUE THREAD

**Issue by glassfishrobot** [javaee/glassfish#18583]
PreCompileJSP Option during Application deployment causes the following error.
But gets deployes without the precompileJSP option
and also same deployment file works on Glassfish 2.1 with the precompile opion without any issues.
—
Error:
[#|2012-03-29T17:32:10.465-0500|INFO|glassfish3.1.1|org.glassfish.admingui|_ThreadID=28;_ThreadName=Thread-2;|Exception Occurred :Error occurred during deployment: E
xception while preparing the app : JSP Compilation Error: org.apache.jasper.JasperException: [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_wa](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_wa)
r/Index.jsp(1,45) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei – [file:/opt/appsvr/glassfish/domains/dom](file:/opt/appsvr/glassfish/domains/dom)
ain1/applications/ccanet/ccanet_war/Index.jsp(1,45) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei. Please
see server.log for more details.
Exception while invoking class com.sun.enterprise.web.WebDeployer prepare method : java.lang.RuntimeException: JSP Compilation Error: org.apache.jasper.JasperExcepti
on: [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45)) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.s
truts.taglib.tiles.UseAttributeTei – [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45)) PWC6112: Failed to load or instantiat
e TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei
JSP Compilation Error: org.apache.jasper.JasperException: [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45)) PWC6112: Failed t
o load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei – [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war)
/Index.jsp(1,45) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei Exception while invoking class com.su
n.enterprise.web.WebDeployer prepare method : java.lang.RuntimeException: JSP Compilation Error: org.apache.jasper.JasperException: [file:/opt/appsvr/glassfish/domain](file:/opt/appsvr/glassfish/domain)
s/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei –
[file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45)) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.stru
ts.taglib.tiles.UseAttributeTei
JSP Compilation Error: org.apache.jasper.JasperException: [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war/Index.jsp(1,45)) PWC6112: Failed t
o load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei – [file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war](file:/opt/appsvr/glassfish/domains/domain1/applications/ccanet/ccanet_war)
/Index.jsp(1,45) PWC6112: Failed to load or instantiate TagExtraInfo class: org.apache.struts.taglib.tiles.UseAttributeTei|#]
------

the index.jsp refered above:
----------------------------
< % @ taglib uri="struts-tiles" prefix="tiles" % >
<tiles:insert template="/core/corePage.jsp">
<tiles:put name="header" content="/core/jsp/layout/header.jsp"/>
<tiles:put name="topNavBar" content="/core/jsp/layout/topNavBar.jsp"/>
<tiles:put name="errorsAndMessages" content="/core/jsp/layout/errorsAndMessages.jsp"/>
<tiles:put name="mainwindow" content="/core/jsp/layout/Index.jsp"/>
</tiles:insert>
#### Environment
SunOS 5.10 Generic_144489-11 i86pc i386 i86pc
Version: GlassFish Server Open Source Edition 3.1.1 (build 12)
#### Affected Versions
[3.1.2_dev]

**Comment by glassfishrobot** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/glassfish/issues/18583
